version: '3.8'

services:
  backend:
    image: tjwkura5/ecommerce_back:latest
    container_name: ecommerce-backend
    environment:
      - DB_HOST=${rds_endpoint}
      - RUN_MIGRATIONS=${run_migrations}
    ports:
      - "8000:8000"
  frontend:
    image: tjwkura5/ecommerce_front:latest
    container_name: ecommerce-frontend
    environment:
    - CHOKIDAR_USEPOLLING=true  # Ensures file watchers work in Docker
    - WDS_SOCKET_PORT=3000     # Use the exposed port for WebSocket connections
    - WDS_SOCKET_HOST=0.0.0.0  # Ensure WebSocket binds to the container's address
    - HOST=0.0.0.0  
    ports:
      - "3000:3000"
    depends_on:
      - backend
