version: '3.8'

services:
  backend:
    image: tjwkura5/ecommerce_back:latest
    container_name: ecommerce-backend
    environment:
      - DB_HOST=${rds_endpoint}
      - RUN_MIGRATIONS=${run_migrations}
    ports:
      - "8000:8000"
  frontend:
    image: tjwkura5/ecommerce_front:latest
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
